language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
sudo: required
addons:
  chrome: stable
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_deploy:
- npm i

script:
  - npm run build:package

deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  api_key:
    secure: ipclqGl8eyAV168zFunWjMArSe+rHhKXzaEsa0JsWC4NdTS/1DquJIcI93McKJBhSbtgJsC82tkyROJdyEB7Fv+kCEY8TNrRQCIZt2VPn4PYszo2YCXHdZVMcTIWTu1AgSImcNGo4j6eKo546n7MRnIfxklStNnZf/F3mWZI/HUJhMgmIRZ8DfTqY0GZT5KwzSOV733vy6/acliy2Apxvnw5L6f9GkWM/gxIkgD2LvT5cUec+dby+WjNaOXsQfOI+YnRMbiGxBvz4/nNrWZzl0tqoZtLyvqFFYyhNy9X3O8G0j1La2W1NZsK3cMmEj0bHa1ppTelQdOMjGkQxmO9o21IYYP+xeU5cNXpGD7h/qyb0q8CTd0B89gFswIQOUsSyIqJLYqdYd2agPA7vHzs1Sb6f94pH0fW6pzGlC7lwe1Wp/6j7FXZm/fghN5ZUdlPc0xAZ83X9H2MGQMlUzkq5EIu96i6nHGH2XOMkmZcXsv9Ou5BxxE0CB4WjHdAggrOap+CaNb+PhaOCVyRA8wLl1eVsaQNVGgm8+4kcoa6qBQQXsJHG+4CmJdrOfDRuzUcbYNHD1wutjoILPAtk6YtSoLF+jrAwiCA4CJTTnYWdn2Bh+bIkpMvR9p/oKZ+Bx6ZwlSqbgI4EjYLKu363S/3qgDANbaTQOqYU4KLaXTEsis=
  on:
    tags: true
    repo: hmcts/hmctsroles-lib
